default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^(tests/fixtures/cassettes/.*|k8s/idf-component-registry/templates/.*)$
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/myint/eradicate/
    rev: 2.3.0
    hooks:
      - id: eradicate
